### ISSUE TITLE
is there a way to install nao_meshes on ROS-melodic?

### ISSUE THREAD

**Issue by yuan0623** [ros-naoqi/nao_meshes#6]
Is it possible to install nao_meshes on ROS-melodic??? I've tried`sudo apt-get install ros-melodic-TAB` , but it seem nao package is not avalable on ROS melodic, is there a way to go around it????

**Comment by mikaelarguedas** [comment]
nao packages have not been released in ROS Melodic yet.
You can build the various packages from source.
In the case of nao_meshes, you should be able to run the indigo installer manually as I dont think it is tied to a given version of ubuntu/ROS: https://github.com/ros-naoqi/nao_meshes_installer/blob/master/naomeshes-0.6.7-linux-installer.run

**Comment by yuan0623** [comment]
Thanks so much for your reply! I've downloaded it and `chmod +x naomeshes-0.6.7-linux-installer.run`, then it turned green in my terminal. And I `sudo ./naomeshes-0.6.7-linux-installer.run`, then nothing happened ...........

**Comment by mikaelarguedas** [comment]
hmmm too bad, it was worth a shot. I just tried on xenial and it worked (but I dont have a bionic environment to test it).
```
wget https://github.com/ros-naoqi/nao_meshes_installer/raw/master/naomeshes-0.6.7-linux-installer.run
chmod +x ./naomeshes-0.6.7-linux-installer.run
./naomeshes-0.6.7-linux-installer.run
```

Not that this is a wizard so you need an X server running to be able to display it and follow the install steps

**Comment by yuan0623** [comment]
Hi, thanks for your help, Still nothing happened.
I'm using Ubuntu 18.04 on VMware player 14.
I'm curious about the X server? is that some kind of background program? Which version should I install in order to display the wizard?

**Comment by arixrobotics** [comment]
I've just tried using Ubuntu 16.04 and Kinetic, and in my case, only the x64 installer works. The other one causes nothing to happen. So maybe you can try this (if you are still trying):
```wget https://github.com/ros-naoqi/nao_meshes_installer/raw/master/naomeshes-0.6.7-linux-x64-installer.run
chmod +x naomeshes-0.6.7-linux-x64-installer.run
./naomeshes-0.6.7-linux-installer.run```

**Comment by saifullah3396** [comment]
For anyone who might be looking at this issue. I have run and tested the solution provided by @mikaelarguedas. It works on ubuntu 18.04 ROS melodic as well.

**Comment by mikaelarguedas** [comment]
`nao_meshes` has been released for ROS Melodic and should be available in the next melodic sync.

If you want to give a try to the package right now you can install it from the [testing repository](http://wiki.ros.org/TestingRepository)

**Comment by robogeekcanada** [comment]
The instructions shown by @arixrobotics works to install the meshes in Ubuntu 20.04, ROS Noetic as well. Thank you!
